/*
 * This class use for show how to use application on each game
 * also tell how to play the game.
 */
package myhilo;

import java.awt.Color;
import static javax.swing.JFrame.EXIT_ON_CLOSE;

/**
 *
 * @author hp
 */
public class HowToPlay extends javax.swing.JFrame {

    /**
     * Creates new form HowToPlay
     */
    private String game = "";
    public HowToPlay(String whatGame) {
        initComponents();
        game = whatGame;
        if(whatGame.equals("CardGame")){
            howToPlayCardGame();
        }
        else if(whatGame.equals("DiceGame")){
            howToPlayDiceGame();
        }else{
            return;
        }
    }
    
    public void howToPlayCardGame(){
        game = "CardGameNext";
        setBackground(Color.BLACK);
        setSize(1200, 600);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        howTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageStart/pathCardreview.png")));
    }
    
    public void howToPlayCardGAameNext(){
        game = "end";
        howTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageStart/pathcardReviewer.png")));
    }
        
    public void howToPlayDiceGame(){
        game = "DiceGameNext";
        setBackground(Color.BLACK);
        setSize(1050, 726);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        howTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageStart/pathHiLoreview.png")));
        
    }
     public void howToPlayDiceGameNext(){
        game = "end";
        howTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageStart/pathHiLoreviewer.png"))); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        howTo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        howTo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        howTo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                howToMouseClicked(evt);
            }
        });
        getContentPane().add(howTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void howToMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howToMouseClicked
        if(game.equals("CardGameNext")){
            howToPlayCardGAameNext();
        } else if (game.equals("DiceGameNext")){
            howToPlayDiceGameNext();
        }else this.setVisible(false);
    }//GEN-LAST:event_howToMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HowToPlay("letHaveFun").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel howTo;
    // End of variables declaration//GEN-END:variables
}
